resources:
- deployment.yml
- service.yml
- postgres-deployment.yml
- postgres-service.yml
- secret.yml
images:
- name: mulenokv/sampleapp
  newTag: main
- name: sample-app
  newName: mulenokv/sampleapp
  newTag: aa9908fd8de072f1bf9aa27d99c87b57c34f9634
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
