apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: mulenokv/sampleapp
  newName: mulenokv/sampleapp
  newTag: 5781a84f90857782eef39827d7fc936541ce7832

resources:
- deployment.yml
- service.yml
- postgres-deployment.yml
- postgres-service.yml
- secret.yml
