resources:
- deployment.yml
- service.yml
- postgres-deployment.yml
- postgres-service.yml
- secret.yml
images:
- name: mulenokv/sampleapp
  newTag: main
- name: sample-app
  newName: mulenokv/sampleapp
  newTag: cd7a07985f82667df71efce39bbe6708048de8f0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
