apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: mulenokv/sampleapp
  newName: mulenokv/sampleapp
  newTag: 301c8405166a114f9a070dc2f7183f47d72836ba

resources:
- deployment.yml
- service.yml
- postgres-deployment.yml
- postgres-service.yml
- secret.yml
