apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: mulenokv/sampleapp
  newName: mulenokv/sampleapp
  newTag: ec50c083780e737073ed0018ecf3b433c2577f12

resources:
- deployment.yml
- service.yml
- postgres-deployment.yml
- postgres-service.yml
- secret.yml
