apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: mulenokv/sampleapp
  newName: mulenokv/sampleapp
  newTag: 4969e222e31780d841125c7a216acbbde01fabce

resources:
- deployment.yml
- service.yml
- postgres-deployment.yml
- postgres-service.yml
- secret.yml
