resources:
- deployment.yml
- service.yml
- postgres-deployment.yml
- postgres-service.yml
- secret.yml
images:
- name: sample-app
  newName: mulenokv/sampleapp
  newTag: 432023d3dfe3dcce316679555af0f3fe3704f150
- name: sampleapp
  newTag: main
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
