apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: mulenokv/sampleapp
  newName: mulenokv/sampleapp
  newTag: 382a9ba805d46deea3fbc84cafad43a3773b79fa

resources:
- deployment.yml
- service.yml
- postgres-deployment.yml
- postgres-service.yml
- secret.yml
